/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/[slug]': RouteRecordInfo<'/blog/[slug]', '/blog/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/cp/': RouteRecordInfo<'/cp/', '/cp', Record<never, never>, Record<never, never>>,
    '/cp/posts/': RouteRecordInfo<'/cp/posts/', '/cp/posts', Record<never, never>, Record<never, never>>,
    '/cp/posts/[id]/edit': RouteRecordInfo<'/cp/posts/[id]/edit', '/cp/posts/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cp/posts/create': RouteRecordInfo<'/cp/posts/create', '/cp/posts/create', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
  }
}
